sudo: required 
language: cpp
addons:
  apt_packages:
    - libirrlicht1.7a
    - libirrlicht-dev
    - libxxf86vm-dev
    - freeglut3-dev
  coverity_scan:
    project:
      name: "projectchrono/chrono"
      description: "Build submitted via Travis CI"
      notification_email: dev@aas.io
      build_command_prepend: "mkdir build && cd build && cmake $CMAKE_EXTRA_FLAGS .."
      build_command: "make -j 4"
      branch_pattern: coverity_scan
compiler:
  - gcc
  - clang
env:
  matrix:
    - CMAKE_EXTRA_FLAGS="-DENABLE_MODULE_IRRLICHT=OFF -DENABLE_MODULE_FEA=OFF -DENABLE_MODULE_POSTPROCESS=OFF"
    - CMAKE_EXTRA_FLAGS="-DENABLE_MODULE_IRRLICHT=ON  -DENABLE_MODULE_FEA=ON  -DENABLE_MODULE_POSTPROCESS=ON"
    - CMAKE_EXTRA_FLAGS="-DENABLE_MODULE_IRRLICHT=ON  -DENABLE_MODULE_FEA=ON  -DENABLE_MODULE_POSTPROCESS=ON  -DENABLE_CXX11=ON"
  global:
    - secure: "YY9gwr3+p3xwX7Kaw+j51JKjYdNl2oNBIHOBfXwLzVCh6F+HVIQAT7C9nSFH4O+brImwhDe7q3BzI1m0hdU5L1nyKtPjG5eolRafkvZYIVjvNduh65OS1rIzV9JibmEjqE6I9x1ndYaW3Yc8tdR6TVr+M2UK907jrBClUdv1uwE="
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq libstdc++-4.8-dev; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8-dev; fi
  - if [ "$CXX" = "g++" ]; then export CMAKE_COMPILER_FLAGS="-DCMAKE_CXX_COMPILER=/usr/bin/g++-4.8 -DCMAKE_CC_COMPILER=/usr/bin/gcc-4.8"; fi 
before_script:
  - mkdir build && cd build
  - cmake $CMAKE_EXTRA_FLAGS $CMAKE_COMPILER_FLAGS ..
script:
  - make -j 4
  - make test
branches:
  - except:
    - feature/mpi
notifications:
  recipients:
    - projectchrono-developers@googlegroups.com
  email:
    on_success: change
    on_failure: always
  irc:
    channels:
      - chat.freenode.net#projectchrono
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
  slack:
    secure: BoCl/C15tcYX+55PQWPBEVCt/nw3j07qONSNecvuUEJ6UbyUKPbt+0HT0Vc2q6f7uphvvw8hRkTyk0XEGEcXAccmRJr9RsOCBvd3kQPdidooDBJ4dI1ZU9y2XcFUjB5VJuKzPgBYSfQSLbt1OVBNZ6ISw02UF1JNaC9DKtFRtSI=
