c_compiler:
  - clang     # [osx]
  - vs2022    # [win]

cxx_compiler:
  - clangxx   # [osx]
  - vs2022    # [win]

cuda_compiler:
  - cuda-nvcc

cuda_compiler_version: # [not osx]
  - 12.8      # [not osx]

numpy:
  - 1.26
